version: '3'

services:
  db:
    image: mysql:8
    restart: always
    volumes:
      - "dbdata:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: vogdb
      MYSQL_USER: vog
      MYSQL_PASSWORD: password

  loader:
    init: true
    build:
      context: ./loader
    depends_on:
      - db
    volumes:
      - "vogdata:/data"
    environment:
      VOG_DATA: /data
      MYSQL_HOST: db
      MYSQL_DATABASE: vogdb
      MYSQL_USER: vog
      MYSQL_PASSWORD: password


volumes:
  dbdata:
  vogdata:
